# Site
name: "Frank Alcantara"
title: "Frank Alcantara"
description: "Consultoria, treinamento, ensino e desenvolvimento."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl:
google_analytics: "UA-166522939-1"
disqus: ""
mailchimp-list: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Frank:
    name: Frank de Alcantara
    display_name: Frank de Alcantara
    photo: "assets/images/Frank.jpg"
    email: frank.alcantara@gmail.com
    web: https://frankalcantara.com
    twitter: https://twitter.com/frankalcantara
    description: "Pai, marido, professor e engenheiro."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gzip

# TOC Settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
