project:
  type: book
  output-dir: _book

book:
  title: "Transformers: Fundamentos Matemáticos e Implementações"
  author: "Frank Alcantara"
  date: "2025"
  
  chapters:
    - index.qmd
    - chapters/01-fundamentos-matematicos.qmd
    - chapters/02-representacao-linguagem.qmd
    - chapters/03-redes-neurais.qmd
    - chapters/04-word-embeddings.qmd
    - chapters/05-arquitetura-transformer.qmd
    - chapters/06-mecanismos-atencao.qmd
    - chapters/07-implementacoes-avancadas.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: show
    code-tools: true
    citations-hover: true
    footnotes-hover: true
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
    
execute:
  freeze: auto

lang: pt
